# Generated by Django 4.2.6 on 2023-10-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
