# Generated by Django 4.2.6 on 2023-10-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='edit',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
